package services

type Service struct {
	Id uint `json:"id" gorm:"primaryKey"`
	Client_name string `json:"client_name"`
	Client_segment string `json:"client_segment"`
 	Org_level string `json:"org_level"`
 	Mrf_name string `json:"mrf_name"`
 	Filial_name string `json:"filial_name"`
 	Connection_point_address string `json:"connection_point_address"`
	Orpon_gid int `json:"orpon_gid"`
 	Document_number int `json:"document_number"`
 	Status_order string `json:"status_order"`
 	Order_category_type string `json:"order_category_type"`
 	Ord_cms string `json:"ord_cms"`
 	Second_request string `json:"second_request"`
 	Cms_request_id string `json:"cms_request_id"`
	Cms_cid string `json:"cms_cid"`
 	Service_name string `json:"service_name"`
	Service_type string `json:"service_type"`
 	Vpn_id int `json:"vpn_id"`
 	Vpn_name string `json:"vpn_name"`
 	Alias string `json:"alias"`
 	Topology string `json:"topology"`
 	Order_speed int `json:"order_speed"`;
 	As_client int `json:"as_client"`;
 	Subnet string `json:"subnet"`;
	Vlan_name string `json:"vlan_name"`;
	Circuit_Type string `json:"circuit_type"`
	Main_Channel string `json:"main_channel"`
	Rez_Channel_1 string `json:"rez_channel_1"`
	Rez_Channel_2 string `json:"rez_channel_2"`
	Cos string `json:"cos"`
	Bp_Percent int `json:"bp_percent"`
	Bc_Percent int `json:"bc_percent"`
	Np_Percent int `json:"np_percent"`
	Mtu int `json:"mtu"`
	Project_Name string `json:"project_name"`
	Program_Name string `json:"program_name"`
	Virtual_Switch_Name string `json:"virtual_switch_name"`
	Ip_Pool string `json:"ip_pool"`
	Count_Access_Point int `json:"count_access_point"`
	Status_Svc string `json:"status_svc"`
	Max_Esr_Capacity string `json:"max_esr_capacity"`
	Ud_Ud_Name string `json:"ud_ud_name"`
	Ud_Type2 string `json:"ud_type2"`
	Ud_Vendor_Model_Number string `json:"ud_vendor_model_number"`
	Ne_Ud_Name string `json:"ne_ud_name"`
	Mgmt_Ip_Ud string `json:"mgmt_ip_ud"`
	As_Ud int `json:"as_ud"`
	Log_Descr string `json:"log_descr"`
	Log_If_Alias string `json:"log_if_alias"`
	Ud_Name string `json:"ud_name"`
	Kd_Type1 string `json:"kd_type1"`
	Kd_Vendor_Model string `json:"kd_vendor_model"`
	Kd_Name string `json:"kd_name"`
	Host_Name string `json:"host_name"`
	Mgmt_Ip_Kd string `json:"mgmt_ip_kd"`
	As_Kd int `json:"as_kd"`
	Phys_Descr string `json:"phys_descr"`
	Joint_Name string `json:"joint_name"`
	Tspu_Name string `json:"tspu_name"`
	Tspu_Operator string `json:"tspu_operator"`
	Resolution string `json:"resolution"`
	Raspor_Date string `json:"raspor_date"`
	Desired_Date string `json:"desired_date"`
	Author_Name string `json:"author_name"`
	Raspor_Completion_Date string `json:"raspor_completion_date"`
	Raspor_Executor string `json:"raspor_executor"`
	Responsible_Name string `json:"responsible_name"`
	Is_Svcregion string `json:"is_svcregion"`
	Bridge_Domain_Name string `json:"bridge_domain_name"`
	Point_Label_Name string `json:"point_label_name"`
	Remark string `json:"remark"`
	Add_Equip_Name string `json:"add_equip_name"`
	Organization_Name string `json:"organization_name"`
	Digital_Economy string `json:"digital_economy"`
	Ca_Stream_Name string `json:"ca_stream_name"`
	Count_Access_Point_On int `json:"count_access_point_on"`
	Count_Access_Point_Off int `json:"count_access_point_off"`
	As_Rtk int `json:"as_rtk"`
	Rd string `json:"rd"`
	Rti string `json:"rti"`
	Rte string `json:"rte"`
	Ud_Vendor string `json:"ud_vendor"`
	Cms_Ordernumber string `json:"cms_ordernumber"`
	Cms_Linkedordernumber string `json:"cms_linkedordernumber"`
	Cms_Changeorder string `json:"cms_changeorder"`
	Cms_Baseordernumber string `json:"cms_baseordernumber"`
	Cms_Ordertype string `json:"cms_ordertype"`
	Cms_Servicetype string `json:"cms_servicetype"`
	Cms_Count int `json:"cms_count"`
	Cms_Channeltype string `json:"cms_channeltype"`
	Cms_Vpntopology string `json:"cms_vpntopology"`
	Cms_Vpnname string `json:"cms_vpnname"`
	Cms_Vpnid int `json:"cms_vpnid"`
	Cms_Externalnumber string `json:"cms_externalnumber"`
	Cms_Vpnrouting string `json:"cms_vpnrouting"`
	Cms_Speed string `json:"cms_speed"`
	Cms_Speedvalue float64 `json:"cms_speedvalue"`
	Cms_Speedmeasure string `json:"cms_speedmeasure"`
	Cms_Packetlength int `json:"cms_packetlength"`
	Cms_Ipasnetworks string `json:"cms_ipasnetworks"`
	Cms_Ipaddressce string `json:"cms_ipaddressce"`
	Cms_Ipaddresspe string `json:"cms_ipaddresspe"`
	Cms_Ipaddressextdesc string `json:"cms_ipaddressextdesc"`
	Cms_Ipsubnetce string `json:"cms_ipsubnetce"`
	Cms_Qinq string `json:"cms_qinq"`
	Cms_Iscritical string `json:"cms_iscritical"`
	Cms_Serviceclass string `json:"cms_serviceclass"`
	Cms_Iscos string `json:"cms_iscos"`
	Cms_Bccosperc float64 `json:"cms_bccosperc"`
	Cms_Bpcosperc float64 `json:"cms_bpcosperc"`
	Cms_Ncosperc float64 `json:"cms_ncosperc"`
	Cms_Porttype string `json:"cms_porttype"`
	Cms_Vpntrafficcollector string `json:"cms_vpntrafficcollector"`
	Cms_Cosmarking string `json:"cms_cosmarking"`
	Line_Hash string `json:"line_hash"`
}

